export const menuArray = [
  {
    name: "Blue Milk",
    ingredients: ["Bantha milk"],
    id: "item-0",
    quantity: 0,
    price: 5,
    emoji: "🥛",
    category: "Drink",
  },
  {
    name: "Jawa Juice",
    ingredients: ["fruit (?) juice"],
    id: "item-1",
    quantity: 0,
    price: 7,
    emoji: "🍹",
    category: "Drink",
  },
  {
    name: "Bantha Burger",
    ingredients: [
      "Bantha meat",
      "lettuce",
      "tomato",
      "cheese",
      "special sauce",
    ],
    id: "item-2",
    quantity: 0,
    price: 12,
    emoji: "🍔",
    category: "Main Meal",
  },
  {
    name: "Nerf Nuggets",
    ingredients: ["Nerf meat", "breadcrumbs", "spices"],
    id: "item-3",
    quantity: 0,
    price: 8,
    emoji: "🍗",
    category: "Main Meal",
  },
  {
    name: "Wookiee Cookies",
    ingredients: ["Wookiee fur", "flour", "sugar", "chocolate chips"],
    id: "item-4",
    quantity: 0,
    price: 6,
    emoji: "🍪",
    category: "Dessert",
  },
  {
    name: "Hutt Pizza",
    ingredients: ["pizza dough", "tomato sauce", "cheese", "Hutt spices"],
    id: "item-5",
    quantity: 0,
    price: 14,
    emoji: "🍕",
    category: "Main Meal",
  },
  {
    name: "Ewok Stew",
    ingredients: ["Ewok meat", "vegetables", "spices"],
    id: "item-6",
    quantity: 0,
    price: 10,
    emoji: "🍲",
    category: "Main Meal",
  },
  {
    name: "Tatooine Tacos",
    ingredients: [
      "grilled meat",
      "lettuce",
      "tomato",
      "sour cream",
      "guacamole",
    ],
    id: "item-7",
    quantity: 0,
    price: 9,
    emoji: "🌮",
    category: "Main Meal",
  },
]
